# Generated by Django 5.2.6 on 2025-09-22 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_projectgroup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('where', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.projectgroup')),
            ],
        ),
    ]
