# Generated by Django 5.2.6 on 2025-09-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
    ]
